#!/bin/bash

docker pull redis
docker pull docker.io/oburstein/webapp:latest

docker run -d -p 6379:6379 --name redis1 redis
docker run -d --link redis1:redis -p 3000:3000 --name webapp oburstein/webapp

echo "Done launching webapp"